### ISSUE TITLE
breadcrumb hoover

### ISSUE THREAD

**Issue by almeidapaulopt** [RandyLowery/business_theme#1]
when cursor hover "home" it disapears
when cursor hover other links on breadcrumb, navbar grows some pixels

**Comment by RandyLowery** [comment]
Fix It Try updating.

**Comment by almeidapaulopt** [comment]
On hoover in "home" still disappears

![business_theme](https://cloud.githubusercontent.com/assets/22657407/26162681/4e54c8d8-3b1f-11e7-9397-5a677edac195.png)
